export const GET_CLIENTS = "GET_CLIENTS";
export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const CLIENTS_LOADING = "CLIENTS_LOADING";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const VIEW_CLIENT = "VIEW_CLIENT";
export const SET_CURRENT_EDIT_CLIENT = "SET_CURRENT_EDIT_CLIENT";

export const OPEN_EDIT_MODAL = "OPEN_MODAL";
export const CLOSE_EDIT_MODAL = "CLOSE_MODAL";

export const OPEN_DETAILS_MODAL = "OPEN_DETAILS_MODAL";
export const CLOSE_DETAILS_MODAL = "CLOSE_DETAILS_MODAL";
