export const GET_CLIENTS = "GET_CLIENTS";
export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const CLIENTS_LOADING = "CLIENTS_LOADING";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const VIEW_CLIENT = "VIEW_CLIENT";
export const SET_CURRENT_EDIT_CLIENT = "SET_CURRENT_EDIT_CLIENT";
